### ISSUE TITLE
Bootstrap website

### ISSUE THREAD

**Issue by pghosh** [Data4Democracy/indivisible#15]
This task is to bootstrap website structure with twitter bootstrap and javascript.

**Comment by pghosh** [comment]
we will be using mongo/express/angular/node stack (MEAN)

**Comment by wwymak** [comment]
Angular 1 or 2?

**Comment by pghosh** [comment]
Lets do angular2 ,since we are writing from scratch.

**Comment by Phinneas** [comment]
I could take a crack at this. I do have some experience with MEAN, but I used angular 1 instead.

**Comment by pghosh** [comment]
@Phinneas I found this article https://scotch.io/tutorials/mean-app-with-angular-2-and-the-angular-cli . Might be helpful with the angular2 part?

**Comment by josephpd3** [comment]
I'm open to helping with this come my Spring Break (April 14-23)! After that, my semester will be winding down and I will be more and more available. I've done production work with Angular 1 before and played with Angular 2 a few times. Mongo is the only aspect of MEAN/Bootstrap I'm unfamiliar with, but it doesn't seem too far out from stuff I've used before when integrating DBs with Angular.

Edit: I'm looking at Angular 2 now, and I'm open to working on a PR for this prior to my break as I am available, or contributing to existing work. @pghosh are there any explicit requirements or prereqs outside of Angular2 and Bootstrap as a base? I see we're waiting on a mock-up for the action page in [Issue #16](https://github.com/Data4Democracy/indivisible/issues/16).
