### ISSUE TITLE
Module naming conventions

### ISSUE THREAD

**Issue by eenblam** [Data4Democracy/indivisible#18]
Given what I've read from the operational discussions, I'm assuming that indivisible will be deployed to Linux. With that in mind, is anyone opposed to `git config core.ignorecase false`?

**Comment by pghosh** [comment]
I think that is reasonable.

**Comment by eenblam** [comment]
Copypasta from Slack: I'm an idiot. Recently got my first Mac. So used to Linux that I assumed that the filesystem was case sensitive, and that this was due to someone pushing from Windows. Sorry.

The solution was to [use git mv ... -f](http://stackoverflow.com/a/21733473/2074215).

**Comment by pghosh** [comment]
Yea, mac is not case sensitive, and file name case becomes an annoyance . Welcome to mac world though :)
